name: CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd Group-4-Interactive-Travel-Map-Application/frontend && npm install
      - run: cd Group-4-Interactive-Travel-Map-Application/frontend && npm test -- --watchAll=false

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: cd Group-4-Interactive-Travel-Map-Application/backend && mvn test
